CREATE TABLE "companies" (
	"company_id" text PRIMARY KEY NOT NULL,
	"vendor_id" text NOT NULL,
	"name" text NOT NULL,
	"historical_names" jsonb,
	"place_type" "place_type",
	"in_business" boolean,
	"verified_on" timestamp,
	"created_at" timestamp DEFAULT now(),
	"street" text,
	"city" text,
	"state" text,
	"postal_code" text,
	"country_code" text,
	"mailing_address" text,
	"mailing_address_city" text,
	"mailing_address_state" text,
	"mailing_address_postal_code" text,
	"latitude" numeric,
	"longitude" numeric,
	"geo_match_level" "geo_match_level",
	"location_linkage" jsonb,
	"primary_sic_code_id" integer,
	"sic_code_ids" jsonb,
	"primary_naics_code_id" integer,
	"naics_code_ids" jsonb,
	"phone" text,
	"fax_number" text,
	"website" text,
	"contacts_count" integer,
	"primary_contact" jsonb,
	"location_employee_count" integer,
	"estimated_location_employee_count" integer,
	"location_sales_volume" integer,
	"square_footage" integer,
	"white_collar_percentage" integer,
	"population_density" numeric,
	"wealthy_area_flag" boolean,
	"headquarters_id" text,
	"ancestor_headquarters_ids" jsonb,
	"cbsa_code" integer,
	"cbsa_level" integer,
	"csa_code" integer,
	"census_block" integer,
	"census_tract" integer,
	"fips_code" integer,
	"greenscore" integer,
	"last_updated_at" timestamp DEFAULT now() NOT NULL
);
